name: httomolibgpu zenodo tests
on:
  pull_request:
    types: [ labeled ]

jobs:
  iris-gpu:
    if: ${{ github.event.label.name == 'run-zenodo-tests' }}
    runs-on: iris-gpu
    container:
      image: nvidia/cuda:12.6.3-devel-ubi8
      env:
        NVIDIA_VISIBLE_DEVICES: ${{ env.NVIDIA_VISIBLE_DEVICES }}
      options: --gpus all --runtime=nvidia

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Create conda environment
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: httomo
          create-args: >-
            cupy==12.3.0
          post-cleanup: 'all'
          init-shell: bash

      - name: Install httomolibgpu
        run: |
          pip install .[dev]
          micromamba list

      - name: Download and run Zenodo tests
        run: |
          chmod +x ./.scripts/download_zenodo.py
          ./.scripts/download_zenodo.py zenodo-tests/large_data_archive
          pytest zenodo-tests/
